// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuOl1DwOQJeAoTswxPqkChTnCo-7IykGI',
    appId: '1:122142967510:web:5a766b97beb876bb08eb77',
    messagingSenderId: '122142967510',
    projectId: 'health-mate-65199',
    authDomain: 'health-mate-65199.firebaseapp.com',
    storageBucket: 'health-mate-65199.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZne4Gu5iIwNQhKyWJ88AkEcbSpi55Af0',
    appId: '1:122142967510:android:ea40845d44b4e02708eb77',
    messagingSenderId: '122142967510',
    projectId: 'health-mate-65199',
    storageBucket: 'health-mate-65199.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLCbni6_TnVHa9aLca3ZzxR4LIYAsFzPg',
    appId: '1:122142967510:ios:46b65f16790cfee408eb77',
    messagingSenderId: '122142967510',
    projectId: 'health-mate-65199',
    storageBucket: 'health-mate-65199.firebasestorage.app',
    iosBundleId: 'com.example.healthMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLCbni6_TnVHa9aLca3ZzxR4LIYAsFzPg',
    appId: '1:122142967510:ios:46b65f16790cfee408eb77',
    messagingSenderId: '122142967510',
    projectId: 'health-mate-65199',
    storageBucket: 'health-mate-65199.firebasestorage.app',
    iosBundleId: 'com.example.healthMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuOl1DwOQJeAoTswxPqkChTnCo-7IykGI',
    appId: '1:122142967510:web:f4e13a23e741adc308eb77',
    messagingSenderId: '122142967510',
    projectId: 'health-mate-65199',
    authDomain: 'health-mate-65199.firebaseapp.com',
    storageBucket: 'health-mate-65199.firebasestorage.app',
  );
}
